name: password_manager
description: A secure password manager with login support and Firebase integration.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.16.0
  google_sign_in: ^6.3.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  googleapis: ^13.2.0
  http: ^1.1.0
  image_picker: ^1.0.4
  firebase_storage: ^11.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
