// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeVzX4woIE7oh-KiGl6R4KuDXL0IYP2kM',
    appId: '1:383840777707:web:15c962b70042690a3b15ae',
    messagingSenderId: '383840777707',
    projectId: 'password-manager-app-b9e66',
    authDomain: 'password-manager-app-b9e66.firebaseapp.com',
    storageBucket: 'password-manager-app-b9e66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCPj5_a4MdOWv3kGj9fSoeG5R0Yb_QEA',
    appId: '1:383840777707:android:503ccdaed5b1a20e3b15ae',
    messagingSenderId: '383840777707',
    projectId: 'password-manager-app-b9e66',
    storageBucket: 'password-manager-app-b9e66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZJTO4aPgGqoSPxSm5HE2ImEfbIS7weZg',
    appId: '1:383840777707:ios:96a8cb28359d961d3b15ae',
    messagingSenderId: '383840777707',
    projectId: 'password-manager-app-b9e66',
    storageBucket: 'password-manager-app-b9e66.firebasestorage.app',
    androidClientId: '383840777707-a40m2l009h3cidnn9728gc7f3i7o9uj0.apps.googleusercontent.com',
    iosClientId: '383840777707-d98q725stdvtfqqe7se51pbcqadpstpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZJTO4aPgGqoSPxSm5HE2ImEfbIS7weZg',
    appId: '1:383840777707:ios:96a8cb28359d961d3b15ae',
    messagingSenderId: '383840777707',
    projectId: 'password-manager-app-b9e66',
    storageBucket: 'password-manager-app-b9e66.firebasestorage.app',
    androidClientId: '383840777707-a40m2l009h3cidnn9728gc7f3i7o9uj0.apps.googleusercontent.com',
    iosClientId: '383840777707-d98q725stdvtfqqe7se51pbcqadpstpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeVzX4woIE7oh-KiGl6R4KuDXL0IYP2kM',
    appId: '1:383840777707:web:15c962b70042690a3b15ae',
    messagingSenderId: '383840777707',
    projectId: 'password-manager-app-b9e66',
    authDomain: 'password-manager-app-b9e66.firebaseapp.com',
    storageBucket: 'password-manager-app-b9e66.firebasestorage.app',
  );

}